### ISSUE TITLE
Build errors with Xcode 13.0

### ISSUE THREAD

**Issue by tonyarnold** [stacksift/SDK#4] opened 2021-09-14 22:39 UTC
https://github.com/stacksift/SDK/blob/52dfaecbbb4e0c57f3068ed443360a00c2d77a24/Sources/Stacksift/MetricKitSubscriber.swift#L30

As usual, Xcode x.0 ships without the necessary SDK for the upcoming major macOS release. This means that availability checks for that version don't work anymore, causing compile errors when building using the Xcode RC. 

Not sure if you want to bump the check to the nonsense future version that Apple seem to use (99999?) - I'm happy to help with a PR.

**Comment by mattmassicotte** [comment] 2021-09-15 00:18
This is an incredibly frustrating issue. I don't there is actually is a way to use Swift conditional compilation to guard against SDK version. I ran this by the Swift team at WWDC, and they did not have a better option for me. The issue is this line:

```swift
#if os(iOS) || (os(macOS) && swift(>=5.5))
```

The Swift version was used as a poor way to check for the Xcode version, which was a proxy for SDK availability. As of right now, I'm unsure how to correctly handle this without just removing it altogether and/or waiting for a **new** Xcode build that does include a macOS beta release.  And, even then, there would have to be another Swift version bump for this check to work correctly...

**Comment by tonyarnold** [comment] 2021-09-15 00:26
Even if you wait for a new Xcode build that ships Swift 5.5.x, and includes the macOS 12.0 SDK, there'll still be _this_ build of Xcode floating around out there, released. 

Frustrating, indeed!

**Comment by mattmassicotte** [comment] 2021-09-15 00:39
Ok, this is now fixed on the main branch. I'm going to do some more digging to see if I can come up with a better solution, as I would like MetricKit for my own app, built now, when running on 12.0.

**Comment by tonyarnold** [comment] 2021-09-15 01:30
Thanks, Matt!

**Comment by mattmassicotte** [comment] 2021-09-15 15:07
Ok, this should be fully resolved in 0.3.5 https://github.com/stacksift/SDK/releases/tag/0.3.5

That version will use and support MetricKit in versions of Xcode that also support it, but it will be fully disabled if building with a version of Xcode that does not (like Xcode 13 RC)

**Closed by mattmassicotte** 2021-09-15 15:07 UTC
